services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    networks:
      - sbk-avro-net


  broker:
    image: confluentinc/cp-kafka:7.7.0
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
    networks:
      - sbk-avro-net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.0
    container_name: schema-registry
    depends_on:
      - broker
    hostname: schema-registry
    ports:
      - "8081:8081"
    restart: always
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - sbk-avro-net

  kowl:
    container_name: kowl
    image: docker.redpanda.com/redpandadata/console:v2.7.0
    depends_on:
      - schema-registry
    restart: always
    ports:
      - "9090:8080"
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["broker:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://schema-registry:8081"]
    networks:
      - sbk-avro-net

  mysql-server:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql-sbk-tx-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - sbk-avro-net

  kafka-init:
    image: confluentinc/cp-kafka:7.7.0
    user: root
    depends_on:
      - broker
      - schema-registry
    volumes:
      - ./kafka/schemas:/schemas
      - ./kafka/kafka-init.sh:/kafka-init.sh
    entrypoint: bash
    command: -c "yum install -y jq nc && chmod +x /kafka-init.sh && /kafka-init.sh"
    networks:
      - sbk-avro-net
    restart: "no"

volumes:
  mysql-sbk-tx-data:

networks:
  sbk-avro-net:
